// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#include "control.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace surrogate {
namespace grpc {
}  // namespace grpc
}  // namespace surrogate
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_control_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_2eproto = nullptr;
const uint32_t TableStruct_control_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_control_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcontrol.proto\022\016surrogate.grpc\032\021msgs_co"
  "mmon.proto\032\022msgs_control.proto\032\021msgs_mot"
  "ion.proto2\273\001\n\016ControlService\022L\n\005MoveJ\022\034."
  "surrogate.grpc.MoveJRequest\032#.surrogate."
  "grpc.ControlDefaultReply\"\000\022[\n\016SetMobileS"
  "tate\022%.surrogate.grpc.SetMobileStateRequ"
  "est\032 .surrogate.grpc.MobileMotionData\"\000b"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_control_2eproto_deps[3] = {
  &::descriptor_table_msgs_5fcommon_2eproto,
  &::descriptor_table_msgs_5fcontrol_2eproto,
  &::descriptor_table_msgs_5fmotion_2eproto,
};
static ::_pbi::once_flag descriptor_table_control_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_2eproto = {
    false, false, 287, descriptor_table_protodef_control_2eproto,
    "control.proto",
    &descriptor_table_control_2eproto_once, descriptor_table_control_2eproto_deps, 3, 0,
    schemas, file_default_instances, TableStruct_control_2eproto::offsets,
    nullptr, file_level_enum_descriptors_control_2eproto,
    file_level_service_descriptors_control_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_2eproto_getter() {
  return &descriptor_table_control_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_2eproto(&descriptor_table_control_2eproto);
namespace surrogate {
namespace grpc {

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
