// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motion.proto

#include "motion.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace surrogate {
namespace grpc {
}  // namespace grpc
}  // namespace surrogate
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_motion_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_motion_2eproto = nullptr;
const uint32_t TableStruct_motion_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_motion_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014motion.proto\022\016surrogate.grpc\032\021msgs_com"
  "mon.proto\032\021msgs_motion.proto2\\\n\rMotionSe"
  "rvice\022K\n\rGetMotionData\022\034.surrogate.grpc."
  "EmptyRequest\032\032.surrogate.grpc.MotionData"
  "\"\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_motion_2eproto_deps[2] = {
  &::descriptor_table_msgs_5fcommon_2eproto,
  &::descriptor_table_msgs_5fmotion_2eproto,
};
static ::_pbi::once_flag descriptor_table_motion_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_motion_2eproto = {
    false, false, 170, descriptor_table_protodef_motion_2eproto,
    "motion.proto",
    &descriptor_table_motion_2eproto_once, descriptor_table_motion_2eproto_deps, 2, 0,
    schemas, file_default_instances, TableStruct_motion_2eproto::offsets,
    nullptr, file_level_enum_descriptors_motion_2eproto,
    file_level_service_descriptors_motion_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_motion_2eproto_getter() {
  return &descriptor_table_motion_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_motion_2eproto(&descriptor_table_motion_2eproto);
namespace surrogate {
namespace grpc {

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
