// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs_common.proto

#include "msgs_common.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace surrogate {
namespace grpc {
PROTOBUF_CONSTEXPR EmptyRequest::EmptyRequest(
    ::_pbi::ConstantInitialized) {}
struct EmptyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyRequestDefaultTypeInternal() {}
  union {
    EmptyRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyRequestDefaultTypeInternal _EmptyRequest_default_instance_;
PROTOBUF_CONSTEXPR EmptyReply::EmptyReply(
    ::_pbi::ConstantInitialized) {}
struct EmptyReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyReplyDefaultTypeInternal() {}
  union {
    EmptyReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyReplyDefaultTypeInternal _EmptyReply_default_instance_;
PROTOBUF_CONSTEXPR DefaultReply::DefaultReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DefaultReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DefaultReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DefaultReplyDefaultTypeInternal() {}
  union {
    DefaultReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DefaultReplyDefaultTypeInternal _DefaultReply_default_instance_;
}  // namespace grpc
}  // namespace surrogate
static ::_pb::Metadata file_level_metadata_msgs_5fcommon_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msgs_5fcommon_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msgs_5fcommon_2eproto = nullptr;

const uint32_t TableStruct_msgs_5fcommon_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::surrogate::grpc::EmptyRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::surrogate::grpc::EmptyReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::surrogate::grpc::DefaultReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::surrogate::grpc::DefaultReply, _impl_.command_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::surrogate::grpc::EmptyRequest)},
  { 6, -1, -1, sizeof(::surrogate::grpc::EmptyReply)},
  { 12, -1, -1, sizeof(::surrogate::grpc::DefaultReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::surrogate::grpc::_EmptyRequest_default_instance_._instance,
  &::surrogate::grpc::_EmptyReply_default_instance_._instance,
  &::surrogate::grpc::_DefaultReply_default_instance_._instance,
};

const char descriptor_table_protodef_msgs_5fcommon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021msgs_common.proto\022\016surrogate.grpc\"\016\n\014E"
  "mptyRequest\"\014\n\nEmptyReply\"=\n\014DefaultRepl"
  "y\022-\n\ncommand_id\030\001 \001(\0162\031.surrogate.grpc.C"
  "ommandId*i\n\tCommandId\022\014\n\010CMD_NULL\020\000\022\024\n\020C"
  "MD_SYETEM_RESET\020\001\022\035\n\031CMD_SYSTEM_EMERGENC"
  "Y_STOP\020\002\022\031\n\025CMD_SET_DESIRED_STATE\020d*L\n\013S"
  "ystemState\022\n\n\006SS_OFF\020\000\022\t\n\005SS_ON\020\001\022\017\n\013SS_"
  "RECOVERY\020\002\022\025\n\021SS_EMERGENCY_STOP\020\003b\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_msgs_5fcommon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msgs_5fcommon_2eproto = {
    false, false, 321, descriptor_table_protodef_msgs_5fcommon_2eproto,
    "msgs_common.proto",
    &descriptor_table_msgs_5fcommon_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_msgs_5fcommon_2eproto::offsets,
    file_level_metadata_msgs_5fcommon_2eproto, file_level_enum_descriptors_msgs_5fcommon_2eproto,
    file_level_service_descriptors_msgs_5fcommon_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msgs_5fcommon_2eproto_getter() {
  return &descriptor_table_msgs_5fcommon_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msgs_5fcommon_2eproto(&descriptor_table_msgs_5fcommon_2eproto);
namespace surrogate {
namespace grpc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto);
  return file_level_enum_descriptors_msgs_5fcommon_2eproto[0];
}
bool CommandId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 100:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SystemState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msgs_5fcommon_2eproto);
  return file_level_enum_descriptors_msgs_5fcommon_2eproto[1];
}
bool SystemState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class EmptyRequest::_Internal {
 public:
};

EmptyRequest::EmptyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.EmptyRequest)
}
EmptyRequest::EmptyRequest(const EmptyRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EmptyRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.EmptyRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EmptyRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EmptyRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EmptyRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msgs_5fcommon_2eproto_getter, &descriptor_table_msgs_5fcommon_2eproto_once,
      file_level_metadata_msgs_5fcommon_2eproto[0]);
}

// ===================================================================

class EmptyReply::_Internal {
 public:
};

EmptyReply::EmptyReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.EmptyReply)
}
EmptyReply::EmptyReply(const EmptyReply& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EmptyReply* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.EmptyReply)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EmptyReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EmptyReply::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EmptyReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msgs_5fcommon_2eproto_getter, &descriptor_table_msgs_5fcommon_2eproto_once,
      file_level_metadata_msgs_5fcommon_2eproto[1]);
}

// ===================================================================

class DefaultReply::_Internal {
 public:
};

DefaultReply::DefaultReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:surrogate.grpc.DefaultReply)
}
DefaultReply::DefaultReply(const DefaultReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DefaultReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.command_id_ = from._impl_.command_id_;
  // @@protoc_insertion_point(copy_constructor:surrogate.grpc.DefaultReply)
}

inline void DefaultReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DefaultReply::~DefaultReply() {
  // @@protoc_insertion_point(destructor:surrogate.grpc.DefaultReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DefaultReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DefaultReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DefaultReply::Clear() {
// @@protoc_insertion_point(message_clear_start:surrogate.grpc.DefaultReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DefaultReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .surrogate.grpc.CommandId command_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_command_id(static_cast<::surrogate::grpc::CommandId>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DefaultReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:surrogate.grpc.DefaultReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_command_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:surrogate.grpc.DefaultReply)
  return target;
}

size_t DefaultReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:surrogate.grpc.DefaultReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .surrogate.grpc.CommandId command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_command_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DefaultReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DefaultReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DefaultReply::GetClassData() const { return &_class_data_; }


void DefaultReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DefaultReply*>(&to_msg);
  auto& from = static_cast<const DefaultReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:surrogate.grpc.DefaultReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command_id() != 0) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DefaultReply::CopyFrom(const DefaultReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:surrogate.grpc.DefaultReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DefaultReply::IsInitialized() const {
  return true;
}

void DefaultReply::InternalSwap(DefaultReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.command_id_, other->_impl_.command_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DefaultReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msgs_5fcommon_2eproto_getter, &descriptor_table_msgs_5fcommon_2eproto_once,
      file_level_metadata_msgs_5fcommon_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace surrogate
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::surrogate::grpc::EmptyRequest*
Arena::CreateMaybeMessage< ::surrogate::grpc::EmptyRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::surrogate::grpc::EmptyRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::surrogate::grpc::EmptyReply*
Arena::CreateMaybeMessage< ::surrogate::grpc::EmptyReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::surrogate::grpc::EmptyReply >(arena);
}
template<> PROTOBUF_NOINLINE ::surrogate::grpc::DefaultReply*
Arena::CreateMaybeMessage< ::surrogate::grpc::DefaultReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::surrogate::grpc::DefaultReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
